name: course-part-3

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: pwd && ls -al
      - uses: actions/checkout@v4
      - name: reprint
        run: pwd && ls -al
      - run: go version
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go version
      - run:
          ls
          go build
          ls
          go test
        workflow-directory: upper
        name: build and test
  
